/*COURSE*/
INSERT INTO "course"("YEAR", "SEMESTER", "COURSE_ID_PREFIX", "COURSE_ID_NO", "DIVISION_NO", "COURSE_NAME", "PROF_ID", "BUILDNO", "ROOMNO", "CREDIT", "COURSE_ID", "MAX_ENROLLEES") VALUES (2019, 1, 'COM', '1111', 1,'DATABASE', '1111111111', '공A', '101', 3, 1, 80);

/*FACULTY*/
INSERT INTO "faculty"("ID", "NAME", "MAJOR_ID", "POSITION") VALUES ('1111111111', 'PROF1', 'COM', '정교수');

/*COURSE_TO_TIME*/
INSERT INTO "course_to_time"("COURSE_ID", "DAY_OF_WEEK", "NO") VALUES (1, 'THU', 1);

/*STUDENTS*/
INSERT INTO "students"("ADMISSION_YEAR", "GRADE", "MAJOR_ID", "STUDENT_ID", "NAME") VALUES (2019, 1, 'COM', '2019999999', 'STUDENT1');

/*GRADE*/
INSERT INTO "grade"("COURSE_ID", "GRADE", "STUDENT_ID") VALUES (1, '4.3', '2019999999');

/*ATTENDANCE*/
INSERT INTO "attendance"("COURSE_ID", "STUDENT_ID", "ABSENCE_TIME") VALUES (1, '2019999999', 1);

/*COURSE_REGISTRATION*/
INSERT INTO "course_registration"("COURSE_ID", "STUDENT_ID") VALUES (1, '2019999999');
