SELECT A."COURSE_NAME" 
FROM course as A, course_registration as B 
WHERE A."COURSE_ID" = B."COURSE_ID" and B."STUDENT_ID" in (
SELECT D."STUDENT_ID" 
FROM course as C, course_registration as D 
WHERE C."COURSE_ID" = D."COURSE_ID" 
GROUP BY D."STUDENT_ID" 
HAVING COUNT(D."STUDENT_ID") > 1) 
GROUP BY A."COURSE_NAME" 
ORDER BY COUNT(B."STUDENT_ID") DESC 
LIMIT 3;