SELECT
  A."YEAR"
  , B."MAJOR_NAME"
  , COUNT(A."COURSE_ID_PREFIX") AS "NUM_COURSE"
FROM
  course AS A
  , college AS B
WHERE
  A."COURSE_ID_PREFIX" = B."MAJOR_ID"
  AND B."MAJOR_NAME" != '교양'
GROUP BY
  A."YEAR"
  , B."MAJOR_NAME"
ORDER BY
  A."YEAR"
  , COUNT(A."COURSE_ID_PREFIX") DESC;
